function sys = mylinearize(io,op)
% MYLINEARIZE Linearize the Simulink model - LIN_F16Block.
%
% SYS = MYLINEARIZE(IO,OP) linearizes the Simulink model LIN_F16Block
% using the analysis I/Os IO about the operating point OP.

% MATLAB(R) file generated by MATLAB(R) 9.9 and Simulink Control Design (TM) 5.6.
%
% Generated on: 31-Jan-2021 13:15:06

%% Specify the model name
model = 'LIN_F16Block';

%% Linearize the model
sys = linearize(model,io,op);

%% Plot the resulting linearization
step(sys)

